debug: false
management:
  endpoints:
    web:
      exposure:
        exclude: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder : traxw

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/board
    username : chang
    password : qwer1234
    driver-class-name : com.mysql.cj.jdbc.Driver
jpa:
  defer-datasource-initialization : true
  hibernate.ddl-auto: create
#  open-in-view : false
  show-sql : true
  properties:
    hibernate.format_sql : true
    hibernate.default branch_fetch_size : 100
  h2.console.enabled : false
  sql.init.mode : always
  data.rest:
    base-path : /api
    detection-strategy: annotated

---
spring:
  config.activate.on-cloud-platform: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none
---